services:
  - type: web
    name: my-python-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run appRender1.py
    pythonVersion: 3.10.11
